---
apiVersion: v1
kind: Service
metadata:
  name: testvm
spec:
  clusterIP: None
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  selector:
    name: fedora
  type: ClusterIP
